server:
  port: ${DATASCALPEL_ENGINE_PORT:8081}

spring:
  application:
    name: data-scalpel-service-engine
  datasource:
    url: ${DATASCALPEL_ENGINE_DB_URL}
    username: ${DATASCALPEL_ENGINE_DB_USERNAME}
    password: ${DATASCALPEL_ENGINE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  super-api-studio:
    view-enabled: true
    security:
      management-auth-enabled: true
    embedded:
      propagate-published-execution-errors: true

data-scalpel:
  engine:
    code: ${DATASCALPEL_ENGINE_CODE}
    management-token: ${DATASCALPEL_ENGINE_MANAGEMENT_TOKEN}
    query:
      default-page-size: ${DATASCALPEL_ENGINE_QUERY_DEFAULT_PAGE_SIZE:20}
      maximum-page-size: ${DATASCALPEL_ENGINE_QUERY_MAXIMUM_PAGE_SIZE:100}
      maximum-filter-count: ${DATASCALPEL_ENGINE_QUERY_MAXIMUM_FILTER_COUNT:50}
      maximum-filter-depth: ${DATASCALPEL_ENGINE_QUERY_MAXIMUM_FILTER_DEPTH:5}
      maximum-in-values: ${DATASCALPEL_ENGINE_QUERY_MAXIMUM_IN_VALUES:1000}
      maximum-offset: ${DATASCALPEL_ENGINE_QUERY_MAXIMUM_OFFSET:100000}
      timeout-seconds: ${DATASCALPEL_ENGINE_QUERY_TIMEOUT_SECONDS:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

info:
  application:
    name: ${spring.application.name}
    version: '@project.version@'
