import { requestJson } from '../../../shared/api/http';
import type { PageResponse } from '../../../shared/api/pageResponse';
import { toSearchParams, type SearchRequest } from '../../../shared/search';
import type { McpAccessToken, McpAccessTokenDetail, McpAccessTokenIssued, McpAuthorizedServer, McpDraftExecution, McpInvocation, McpInvocationOverview, McpRelease, McpServer, McpTool, McpToolSummary, SaveMcpAccessTokenRequest, SaveMcpServerRequest, SaveMcpToolRequest } from '../model/mcp';
const SERVERS = '/v1/mcp-servers';
const ACCESS_TOKENS = '/v1/mcp-access-tokens';
const withSearch = (path: string, request: SearchRequest) => { const query = toSearchParams(request).toString(); return query ? `${path}?${query}` : path; };
export const fetchMcpServers = (request: SearchRequest) => requestJson<PageResponse<McpServer>>(withSearch(SERVERS, request));
export const fetchMcpServer = (id: string) => requestJson<McpServer>(`${SERVERS}/${id}`);
export const createMcpServer = (request: SaveMcpServerRequest) => requestJson<McpServer>(SERVERS, { method: 'POST', body: JSON.stringify(request) });
export const updateMcpServer = (id: string, request: SaveMcpServerRequest) => requestJson<McpServer>(`${SERVERS}/${id}/actions/update`, { method: 'POST', body: JSON.stringify(request) });
export const serverAction = (id: string, action: 'publish' | 'enable' | 'disable') => requestJson<McpServer>(`${SERVERS}/${id}/actions/${action}`, { method: 'POST' });
export const deleteMcpServer = (id: string) => requestJson<void>(`${SERVERS}/${id}/actions/delete`, { method: 'POST' });
export const fetchMcpTools = (serverId: string) => requestJson<McpToolSummary[]>(`${SERVERS}/${serverId}/tools/summaries`);
export const fetchMcpTool = (serverId: string, toolId: string) => requestJson<McpTool>(`${SERVERS}/${serverId}/tools/${toolId}`);
export const createMcpTool = (serverId: string, request: SaveMcpToolRequest) => requestJson<McpTool>(`${SERVERS}/${serverId}/tools`, { method: 'POST', body: JSON.stringify(request) });
export const updateMcpTool = (serverId: string, toolId: string, request: SaveMcpToolRequest) => requestJson<McpTool>(`${SERVERS}/${serverId}/tools/${toolId}/actions/update`, { method: 'POST', body: JSON.stringify(request) });
export const deleteMcpTool = (serverId: string, toolId: string) => requestJson<void>(`${SERVERS}/${serverId}/tools/${toolId}/actions/delete`, { method: 'POST' });
export const executeMcpDraft = (serverId: string, request: Pick<SaveMcpToolRequest, 'inputSchemaJson' | 'outputSchemaJson' | 'script'> & {
    argumentsJson: string;
}) => requestJson<McpDraftExecution>(`${SERVERS}/${serverId}/tools/actions/execute-draft`, { method: 'POST', body: JSON.stringify(request) }, 20000);
export const fetchMcpAccessTokens = (request: SearchRequest) => requestJson<PageResponse<McpAccessToken>>(withSearch(ACCESS_TOKENS, request));
export const fetchMcpAccessTokenServerCandidates = (request: SearchRequest) => requestJson<PageResponse<McpAuthorizedServer>>(withSearch(`${ACCESS_TOKENS}/server-candidates`, request));
export const fetchMcpAccessToken = (id: string) => requestJson<McpAccessTokenDetail>(`${ACCESS_TOKENS}/${id}`);
export const createMcpAccessToken = (request: SaveMcpAccessTokenRequest) => requestJson<McpAccessTokenIssued>(ACCESS_TOKENS, { method: 'POST', body: JSON.stringify(request) });
export const updateMcpAccessToken = (id: string, request: Omit<SaveMcpAccessTokenRequest, 'serverIds'>) => requestJson<McpAccessToken>(`${ACCESS_TOKENS}/${id}/actions/update`, { method: 'POST', body: JSON.stringify(request) });
export const updateMcpAccessTokenServers = (id: string, serverIds: string[]) => requestJson<McpAccessTokenDetail>(`${ACCESS_TOKENS}/${id}/actions/update-servers`, { method: 'POST', body: JSON.stringify({ serverIds }) });
export const mcpAccessTokenAction = (id: string, action: 'enable' | 'disable') => requestJson<McpAccessToken>(`${ACCESS_TOKENS}/${id}/actions/${action}`, { method: 'POST' });
export const rotateMcpAccessToken = (id: string) => requestJson<McpAccessTokenIssued>(`${ACCESS_TOKENS}/${id}/actions/rotate`, { method: 'POST' });
export const deleteMcpAccessToken = (id: string) => requestJson<void>(`${ACCESS_TOKENS}/${id}/actions/delete`, { method: 'POST' });
export const fetchMcpAccessTokenSecret = (id: string) => requestJson<{ accessToken: string }>(`${ACCESS_TOKENS}/${id}/secret`);
export const fetchServerMcpAccessTokens = (serverId: string, request: SearchRequest) => requestJson<PageResponse<McpAccessToken>>(withSearch(`${SERVERS}/${serverId}/access-tokens`, request));
export const grantServerMcpAccessToken = (serverId: string, accessTokenId: string) => requestJson<void>(`${SERVERS}/${serverId}/actions/grant-access-token`, { method: 'POST', body: JSON.stringify({ accessTokenId }) });
export const revokeServerMcpAccessToken = (serverId: string, accessTokenId: string) => requestJson<void>(`${SERVERS}/${serverId}/actions/revoke-access-token`, { method: 'POST', body: JSON.stringify({ accessTokenId }) });
export const fetchMcpReleases = (id: string) => requestJson<McpRelease[]>(`${SERVERS}/${id}/releases`);
export const fetchMcpInvocations = (request: SearchRequest) => requestJson<PageResponse<McpInvocation>>(withSearch('/v1/mcp-invocations', request));
export const fetchMcpInvocationOverview = () => requestJson<McpInvocationOverview>('/v1/mcp-invocations/statistics/overview');
