import generatedSparkJavaApiIndex from './sparkJavaApiIndex.generated.json';

/** Spark 4.1.1 / DataScalpel Job API v1 index generated by the explicit maintenance tool. */
export interface SparkJavaApiEntry {
  owner: string;
  name: string;
  signature: string;
  returnType: string;
  summary: string;
  snippet: string;
}

export const sparkJavaApiIndex: SparkJavaApiEntry[] = generatedSparkJavaApiIndex;

export const dataScalpelJavaSnippets = [
  {
    label: '读取模型',
    detail: 'DataScalpel SDK · ModelResources',
    documentation: '按任务定义中的模型绑定名读取 Dataset<Row>。',
    insertText: 'context.models().read("${1:bindingName}")',
  },
  {
    label: '读取 JDBC 表',
    detail: 'DataScalpel SDK · JdbcResources',
    documentation: '按 JDBC 绑定名和表名读取 Dataset<Row>。',
    insertText: 'context.jdbc().readTable("${1:bindingName}", "${2:table}")',
  },
  {
    label: '配置 JDBC 分片',
    detail: 'DataScalpel SDK · JdbcReadOptions',
    documentation: '配置 JDBC 源端分片、Fetch Size 和查询超时。',
    insertText: 'JdbcReadOptions.builder()\n\t.partitionBy("${1:id}", "${2:1}", "${3:100000}", ${4:8})\n\t.fetchSize(${5:1000})\n\t.queryTimeoutSeconds(${6:300})\n\t.build()',
  },
  {
    label: '写入模型（同名字段）',
    detail: 'DataScalpel SDK · ModelWriteOperation',
    documentation: '同名映射写入目标模型；checkSchema 仅在本地 TestKit 中校验。',
    insertText: 'context.models()\n\t.write("${1:bindingName}", ${2:dataset})\n\t.mode(ModelWriteMode.${3|APPEND,OVERWRITE,UPSERT|})\n\t.mapSameName()\n\t.checkSchema()\n\t.execute();',
  },
];
