import { requestJson } from '../../../shared/api/http';
import type { PageResponse } from '../../../shared/api/pageResponse';
import { toSearchParams, type SearchRequest } from '../../../shared/search';
import type { Metric, MetricBasics, MetricDefinition, MetricDraft, MetricFieldCandidate, MetricStatus, MetricTask, MetricVersion, TaskMetricRelations } from '../model/metric';
const base = '/v1/metrics';
const query = (request: SearchRequest) => toSearchParams(request).toString();
const post = <T>(path: string, value?: unknown): Promise<T> => requestJson(path, { method: 'POST', ...(value === undefined ? {} : { body: JSON.stringify(value) }) });
export const fetchMetrics = (request: SearchRequest): Promise<PageResponse<Metric>> => requestJson(`${base}?${query(request)}`);
export const fetchMetric = (id: string): Promise<Metric> => requestJson(`${base}/${id}`);
export const fetchMetricDraft = (id: string): Promise<MetricDraft> => requestJson(`${base}/${id}/draft`);
export const createMetric = (value: MetricBasics & { code: string }): Promise<Metric> => post(base, value);
export const updateMetric = (id: string, value: MetricBasics): Promise<Metric> => post(`${base}/${id}/actions/update`, value);
export const saveMetricDraft = (id: string, definition: MetricDefinition, expectedDraftFingerprint: string): Promise<MetricDraft> => post(`${base}/${id}/actions/update-definition`, { definition, expectedDraftFingerprint });
export const publishMetric = (id: string, expectedDraftFingerprint: string, changeNote: string): Promise<Metric> => post(`${base}/${id}/actions/publish`, { expectedDraftFingerprint, changeNote });
export const disableMetric = (id: string): Promise<Metric> => post(`${base}/${id}/actions/disable`);
export const deleteMetric = (id: string): Promise<void> => post(`${base}/${id}/actions/delete`);
export const fetchMetricVersions = (id: string, request: SearchRequest): Promise<PageResponse<MetricVersion>> => requestJson(`${base}/${id}/versions?${query(request)}`);
export const fetchMetricVersion = (id: string, version: number): Promise<MetricVersion> => requestJson(`${base}/${id}/versions/${version}`);
export const fetchMetricTasks = (id: string, request: SearchRequest): Promise<PageResponse<MetricTask>> => requestJson(`${base}/${id}/tasks?${query(request)}`);
export const fetchModelMetrics = (id: string, request: SearchRequest, status: MetricStatus): Promise<PageResponse<Metric>> => requestJson(`/v1/models/${id}/metrics?${query(request)}&status=${status}`);
export const fetchTaskMetrics = (id: string, request: SearchRequest, status: MetricStatus): Promise<TaskMetricRelations> => requestJson(`/v1/tasks/${id}/metrics?${query(request)}&status=${status}`);
export const fetchMetricFields = (modelId: string, request: SearchRequest): Promise<PageResponse<MetricFieldCandidate>> => requestJson(`${base}/model-fields?modelId=${encodeURIComponent(modelId)}&${query(request)}`);
